### ISSUE TITLE
Uplink Error

### ISSUE THREAD

**Issue by yunTaoScripts** [zerynth/demo-ew19-firmware#1]
I can verify code successfully on PSoC6-wifi-BT. But when I uplink, something  wrong happened.
I have completed the step register/create/virtulize.
Can it be network problem?
![image](https://user-images.githubusercontent.com/45733048/57607194-1a1e0100-759d-11e9-9e5f-7f8a501d4658.png)

**Comment by a-pitasi** [comment]
Hi there :grin: 
As I also said there: https://community.zerynth.com/t/uplink-example-error-on-psoc6/2223, the uplink procedure seems fine to me. `telnet` command is used for the communication to the device USB, not a network-related issue. I'm closing this issue, feel free to reopen it or start a new thread on [our forum](https://community.zerynth.com) if you have any further problem, I'll personally look into them :smiley:
